{"abstract":[{"type":"text","text":"White point using Illuminant D50 and 2 degree observer."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"D50_2"}],"platforms":["macOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/d50_2"]},{"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/d50_2"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","title":"ReferenceWhite.D50_2","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"D50_2","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@NixUniversalSDK@E@ReferenceWhite@ReferenceWhiteD50_2","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"text":"ReferenceWhiteD50_2","kind":"identifier"}]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"type":"text","text":"A framework to allow integration of Nix devices into third party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D50_2":{"navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteD50_2"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2","abstract":[{"type":"text","text":"White point using Illuminant D50 and 2 degree observer."}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/d50_2","kind":"symbol","title":"ReferenceWhite.D50_2","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"D50_2","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"kind":"symbol","abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","title":"ReferenceWhite","role":"symbol","url":"\/documentation\/nixuniversalsdk\/referencewhite","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReferenceWhite","kind":"identifier"}],"navigatorTitle":[{"text":"ReferenceWhite","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"ReferenceWhiteD50_2","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"ReferenceWhiteD50_2"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ReferenceWhiteD50_2"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","value":"ReferenceWhiteD50_2","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_2\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_2\/fragments","value":[{"text":"ReferenceWhiteD50_2","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","value":"ReferenceWhite","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","op":"replace","value":[{"kind":"identifier","text":"ReferenceWhite"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}