{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"D50_10","kind":"identifier"}]}]}],"metadata":{"roleHeading":"Case","externalID":"c:@M@NixUniversalSDK@E@ReferenceWhite@ReferenceWhiteD50_10","navigatorTitle":[{"text":"ReferenceWhiteD50_10","kind":"identifier"}],"role":"symbol","symbolKind":"case","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"D50_10"}],"title":"ReferenceWhite.D50_10"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"]]},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/d50_10"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/d50_10"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"White point using Illuminant D50 and 10 degree observer."}],"sections":[],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_10","interfaceLanguage":"swift"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"type":"text","text":"A framework to allow integration of Nix devices into third party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D50_10":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_10","type":"topic","title":"ReferenceWhite.D50_10","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteD50_10"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"D50_10","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/d50_10","abstract":[{"text":"White point using Illuminant D50 and 10 degree observer.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"kind":"symbol","abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","title":"ReferenceWhite","role":"symbol","url":"\/documentation\/nixuniversalsdk\/referencewhite","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReferenceWhite","kind":"identifier"}],"navigatorTitle":[{"text":"ReferenceWhite","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ReferenceWhiteD50_10","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ReferenceWhiteD50_10"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"ReferenceWhiteD50_10","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_10\/title","value":"ReferenceWhiteD50_10"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_10\/fragments","op":"replace","value":[{"text":"ReferenceWhiteD50_10","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","value":"ReferenceWhite","op":"replace"},{"value":[{"text":"ReferenceWhite","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}