{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"]]},"abstract":[{"type":"text","text":"White point using Illuminant F2 and 2 degree observer."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F2_2"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/f2_2"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/f2_2"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"F2_2","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"metadata":{"role":"symbol","title":"ReferenceWhite.F2_2","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteF2_2"}],"externalID":"c:@M@NixUniversalSDK@E@ReferenceWhite@ReferenceWhiteF2_2","symbolKind":"case","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"F2_2","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"type":"text","text":"A framework to allow integration of Nix devices into third party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/F2_2":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F2_2","type":"topic","title":"ReferenceWhite.F2_2","kind":"symbol","navigatorTitle":[{"text":"ReferenceWhiteF2_2","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"F2_2","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/f2_2","abstract":[{"type":"text","text":"White point using Illuminant F2 and 2 degree observer."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"kind":"symbol","abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","title":"ReferenceWhite","role":"symbol","url":"\/documentation\/nixuniversalsdk\/referencewhite","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReferenceWhite","kind":"identifier"}],"navigatorTitle":[{"text":"ReferenceWhite","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ReferenceWhiteF2_2"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ReferenceWhiteF2_2","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ReferenceWhiteF2_2"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"ReferenceWhiteF2_2","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F2_2\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F2_2\/fragments","value":[{"kind":"identifier","text":"ReferenceWhiteF2_2"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","value":"ReferenceWhite"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"kind":"identifier","text":"ReferenceWhite"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}