{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lambda"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"> { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/ispectraldata\/lambda"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/ispectraldata\/lambda"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/lambda","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Wavelength values. Each entry "},{"type":"codeVoice","code":"i"},{"type":"text","text":" in this array corresponds to a spectral value in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/value"},{"type":"text","text":" at the same index."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"lambda"}],"role":"symbol","title":"lambda","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lambda"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">"}],"symbolKind":"property","externalID":"c:@M@NixUniversalSDK@objc(pl)ISpectralData(py)lambda","required":true,"modules":[{"name":"NixUniversalSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/lambda":{"navigatorTitle":[{"kind":"identifier","text":"lambda"}],"role":"symbol","title":"lambda","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lambda"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Wavelength values. Each entry "},{"type":"codeVoice","code":"i"},{"type":"text","text":" in this array corresponds to a spectral value in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/value"},{"type":"text","text":" at the same index."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/lambda","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nixuniversalsdk\/ispectraldata\/lambda"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData":{"role":"symbol","title":"ISpectralData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ISpectralData"}],"abstract":[{"type":"text","text":"Protocol describing spectral data obtained from a measurement"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}],"url":"\/documentation\/nixuniversalsdk\/ispectraldata"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/value":{"navigatorTitle":[{"kind":"identifier","text":"value"}],"role":"symbol","title":"value","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Spectral reflectance values. Each entry "},{"type":"codeVoice","code":"i"},{"type":"text","text":" in this array corresponds to a wavelength value in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/lambda"},{"type":"text","text":" at the same index."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/value","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nixuniversalsdk\/ispectraldata\/value"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A framework to allow integration of Nix devices into third party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"lambda"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"lambda"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"lambda"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1lambda\/title","value":"lambda"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1lambda\/fragments","value":[{"kind":"identifier","text":"lambda"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/title","value":"ISpectralData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/fragments","value":[{"kind":"identifier","text":"ISpectralData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1value\/title","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1value\/fragments","value":[{"kind":"identifier","text":"value"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}