{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/scanmode\/fromuint8(_:)"]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fromUInt8(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Helper to find a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode"},{"type":"text","text":" enum from a "},{"type":"codeVoice","code":"uint8"},{"type":"text","text":" value, or "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA","isActive":true},{"text":" for invalid input.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromUInt8","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"byte","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":"?) -> "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","kind":"typeIdentifier","text":"ScanMode","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"}],"platforms":["macOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode"]]},"metadata":{"role":"symbol","title":"fromUInt8(_:)","roleHeading":"Type Method","externalID":"s:15NixUniversalSDK8ScanModeO9fromUInt8yACs0G0VSgFZ","modules":[{"name":"NixUniversalSDK"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromUInt8"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode","kind":"typeIdentifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/fromUInt8(_:)":{"abstract":[{"text":"Helper to find a ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","type":"reference","isActive":true},{"text":" enum from a ","type":"text"},{"code":"uint8","type":"codeVoice"},{"text":" value, or ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA"},{"type":"text","text":" for invalid input."}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fromUInt8(_:)","url":"\/documentation\/nixuniversalsdk\/scanmode\/fromuint8(_:)","kind":"symbol","title":"fromUInt8(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromUInt8"},{"kind":"text","text":"("},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","kind":"typeIdentifier","text":"ScanMode"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/NA":{"navigatorTitle":[{"text":"ScanModeNA","kind":"identifier"}],"abstract":[{"text":"Unknown \/ undefined conditions","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA","url":"\/documentation\/nixuniversalsdk\/scanmode\/na","kind":"symbol","title":"ScanMode.NA","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"NA","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","navigatorTitle":[{"text":"ScanMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/scanmode","title":"ScanMode","type":"topic","abstract":[{"text":"Enum to describe the measurement modes used by Nix devices","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ScanMode","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"type":"text","text":"A framework to allow integration of Nix devices into third party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1NA\/title","value":"ScanModeNA"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1NA\/fragments","value":[{"text":"ScanModeNA","kind":"identifier"}]},{"value":"ScanMode","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments","value":[{"kind":"identifier","text":"ScanMode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}