{"metadata":{"externalID":"c:@M@NixUniversalSDK@E@ScanMode@ScanModeM0","title":"ScanMode.M0","modules":[{"name":"NixUniversalSDK"}],"role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"M0","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"ScanModeM0","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"M0","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M0","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/scanmode\/m0"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/scanmode\/m0"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode"]]},"kind":"symbol","abstract":[{"text":"M0 conditions (ISO 13655)","type":"text"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/M0":{"navigatorTitle":[{"kind":"identifier","text":"ScanModeM0"}],"abstract":[{"type":"text","text":"M0 conditions (ISO 13655)"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M0","url":"\/documentation\/nixuniversalsdk\/scanmode\/m0","kind":"symbol","title":"ScanMode.M0","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"M0","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","navigatorTitle":[{"text":"ScanMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/scanmode","title":"ScanMode","type":"topic","abstract":[{"text":"Enum to describe the measurement modes used by Nix devices","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ScanMode","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"type":"text","text":"A framework to allow integration of Nix devices into third party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"ScanModeM0","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ScanModeM0"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"ScanModeM0","kind":"identifier"}],"platforms":["macOS"]}]},"op":"replace"},{"op":"replace","value":"ScanModeM0","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M0\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M0\/fragments","value":[{"text":"ScanModeM0","kind":"identifier"}]},{"op":"replace","value":"ScanMode","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments","value":[{"kind":"identifier","text":"ScanMode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}