{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M2"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"M2","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/scanmode\/m2"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/scanmode\/m2"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"ScanModeM2","kind":"identifier"}],"title":"ScanMode.M2","roleHeading":"Case","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"M2","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@E@ScanMode@ScanModeM2","symbolKind":"case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"M2 conditions (ISO 13655)"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","navigatorTitle":[{"text":"ScanMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/scanmode","title":"ScanMode","type":"topic","abstract":[{"text":"Enum to describe the measurement modes used by Nix devices","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ScanMode","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/M2":{"navigatorTitle":[{"kind":"identifier","text":"ScanModeM2"}],"abstract":[{"text":"M2 conditions (ISO 13655)","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/M2","url":"\/documentation\/nixuniversalsdk\/scanmode\/m2","kind":"symbol","title":"ScanMode.M2","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"M2"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"type":"text","text":"A framework to allow integration of Nix devices into third party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ScanModeM2","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ScanModeM2","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"ScanModeM2","kind":"identifier"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ScanMode","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ScanMode"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments"},{"value":"ScanModeM2","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M2\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1M2\/fragments","value":[{"text":"ScanModeM2","kind":"identifier"}],"op":"replace"}]}]}