{"abstract":[{"text":"Enum to describe the available options for density status","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DensityStatus","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Since 4.0.2"}]}]}],"type":"unorderedList"}]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/A","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/E","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/I","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/NONE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/T"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/fullName"],"title":"Instance Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/fromInt(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/fromString(_:)"]},{"generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/Equatable-Implementations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP","doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH","doc:\/\/com.nixsensor.universalsdk\/SY"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/densitystatus"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/densitystatus"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus"},"metadata":{"title":"DensityStatus","symbolKind":"enum","role":"symbol","externalID":"c:@M@NixUniversalSDK@E@DensityStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DensityStatus"}],"navigatorTitle":[{"kind":"identifier","text":"DensityStatus"}],"modules":[{"name":"NixUniversalSDK"}],"roleHeading":"Enumeration"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/A":{"title":"DensityStatus.A","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/A","url":"\/documentation\/nixuniversalsdk\/densitystatus\/a","abstract":[{"type":"text","text":"Status A (ISO 5-3:2009)"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"A","kind":"identifier"}],"navigatorTitle":[{"text":"DensityStatusA","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/fromInt(_:)":{"title":"fromInt(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/fromInt(_:)","url":"\/documentation\/nixuniversalsdk\/densitystatus\/fromint(_:)","abstract":[{"text":"Helper to find a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus"},{"text":" enum from an ","type":"text"},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value, or "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/NONE","isActive":true},{"type":"text","text":" for invalid input."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fromInt","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?) -> "},{"text":"DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","kind":"typeIdentifier"}],"kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ"},"doc://com.nixsensor.universalsdk/s12CaseIterableP":{"title":"Swift.CaseIterable","type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/E":{"title":"DensityStatus.E","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/E","url":"\/documentation\/nixuniversalsdk\/densitystatus\/e","abstract":[{"text":"Status E (ISO 5-3:2009)","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"E","kind":"identifier"}],"navigatorTitle":[{"text":"DensityStatusE","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/T":{"title":"DensityStatus.T","navigatorTitle":[{"text":"DensityStatusT","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/densitystatus\/t","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"T"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/T","abstract":[{"type":"text","text":"Status T (ISO 5-3:2009)"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"type":"text","text":"A framework to allow integration of Nix devices into third party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/RawRepresentable-Implementations","url":"\/documentation\/nixuniversalsdk\/densitystatus\/rawrepresentable-implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic"},"doc://com.nixsensor.universalsdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SH","title":"Swift.Hashable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/Equatable-Implementations":{"title":"Equatable Implementations","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/Equatable-Implementations","url":"\/documentation\/nixuniversalsdk\/densitystatus\/equatable-implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DensityStatus"}],"kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk\/densitystatus","abstract":[{"text":"Enum to describe the available options for density status","type":"text"}],"navigatorTitle":[{"text":"DensityStatus","kind":"identifier"}],"title":"DensityStatus"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/I":{"title":"DensityStatus.I","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/I","url":"\/documentation\/nixuniversalsdk\/densitystatus\/i","abstract":[{"text":"Status I (ISO 5-3:2009)","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"I"}],"navigatorTitle":[{"text":"DensityStatusI","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/fromString(_:)":{"title":"fromString(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/fromString(_:)","url":"\/documentation\/nixuniversalsdk\/densitystatus\/fromstring(_:)","abstract":[{"text":"Helper to find a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus"},{"text":" enum from a ","type":"text"},{"type":"codeVoice","code":"String"},{"text":" value, or ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/NONE","type":"reference"},{"text":" for invalid input.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromString"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?) -> ","kind":"text"},{"text":"DensityStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"}],"kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/NONE":{"title":"DensityStatus.NONE","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/NONE","url":"\/documentation\/nixuniversalsdk\/densitystatus\/none","abstract":[{"text":"Unknown \/ undefined conditions","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NONE"}],"navigatorTitle":[{"kind":"identifier","text":"DensityStatusNONE"}],"kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/init(rawValue:)","url":"\/documentation\/nixuniversalsdk\/densitystatus\/init(rawvalue:)","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/fullName":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/fullName","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk\/densitystatus\/fullname","abstract":[{"type":"text","text":"Helper to get ‘friendly’ name for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus"}],"title":"fullName"},"doc://com.nixsensor.universalsdk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SY","title":"Swift.RawRepresentable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"DensityStatus","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"value":[{"kind":"identifier","text":"DensityStatus"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DensityStatus","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/A","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/E","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/I","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/NONE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/T"]}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DensityStatus","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["macOS"]}]}},{"value":"DensityStatusA","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1A\/title","op":"replace"},{"value":[{"text":"DensityStatusA","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1A\/fragments"},{"value":"DensityStatusE","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1E\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1E\/fragments","value":[{"text":"DensityStatusE","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1T\/title","value":"DensityStatusT","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1T\/fragments","value":[{"kind":"identifier","text":"DensityStatusT"}],"op":"replace"},{"op":"replace","value":"DensityStatus","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/title"},{"value":[{"text":"DensityStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/fragments","op":"replace"},{"value":"DensityStatusI","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1I\/title","op":"replace"},{"value":[{"text":"DensityStatusI","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1I\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1NONE\/title","op":"replace","value":"DensityStatusNONE"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1NONE\/fragments","value":[{"kind":"identifier","text":"DensityStatusNONE"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}