{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceStatus"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicestatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/devicestatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH","doc:\/\/com.nixsensor.universalsdk\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enum describing the possible causes of a device disconnection event in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceStatus"}],"title":"DeviceStatus","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@NixUniversalSDK@E@DeviceStatus","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_DROPPED_CONNECTION","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_INTERNAL","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_MAX_ATTEMPTS","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_TIMEOUT","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_UNAUTHORIZED","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_UNSUPPORTED_DEVICE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/SUCCESS"]},{"title":"Initializers","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/name"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/Equatable-Implementations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus":{"role":"symbol","title":"DeviceStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceStatus"}],"abstract":[{"type":"text","text":"Enum describing the possible causes of a device disconnection event in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceStatus"}],"url":"\/documentation\/nixuniversalsdk\/devicestatus"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/nixuniversalsdk\/devicestatus\/rawrepresentable-implementations"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/ERROR_TIMEOUT":{"role":"symbol","title":"DeviceStatus.ERROR_TIMEOUT","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_TIMEOUT"}],"abstract":[{"type":"text","text":"The device connection attempt was cancelled due to a timeout error."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_TIMEOUT","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceStatusERROR_TIMEOUT"}],"url":"\/documentation\/nixuniversalsdk\/devicestatus\/error_timeout"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/disconnect()":{"navigatorTitle":[{"kind":"identifier","text":"disconnect"}],"role":"symbol","title":"disconnect()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnect"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Disconnect from this Nix device, or cancel a connection attempt currently in progress."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/disconnect()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/disconnect()"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/ERROR_DROPPED_CONNECTION":{"role":"symbol","title":"DeviceStatus.ERROR_DROPPED_CONNECTION","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_DROPPED_CONNECTION"}],"abstract":[{"type":"text","text":"The device has disconnected unexpectedly (possibly due to low Bluetooth signal strength or low battery level)."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_DROPPED_CONNECTION","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceStatusERROR_DROPPED_CONNECTION"}],"url":"\/documentation\/nixuniversalsdk\/devicestatus\/error_dropped_connection"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/ERROR_UNAUTHORIZED":{"role":"symbol","title":"DeviceStatus.ERROR_UNAUTHORIZED","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_UNAUTHORIZED"}],"abstract":[{"type":"text","text":"The device connection attempt was cancelled because the specified device was not authorized for this build of the Nix SDK. Check that the device allocation code and\/or serial number is expected to be authorized for this build."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_UNAUTHORIZED","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceStatusERROR_UNAUTHORIZED"}],"url":"\/documentation\/nixuniversalsdk\/devicestatus\/error_unauthorized"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"String representation of this "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/name","kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk\/devicestatus\/name"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/ERROR_INTERNAL":{"role":"symbol","title":"DeviceStatus.ERROR_INTERNAL","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_INTERNAL"}],"abstract":[{"type":"text","text":"The device has disconnected for an unknown reason (internal SDK error)."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_INTERNAL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceStatusERROR_INTERNAL"}],"url":"\/documentation\/nixuniversalsdk\/devicestatus\/error_internal"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"role":"symbol","title":"IDeviceCompat","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDeviceCompat"}],"abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" objects are found nearby using the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDeviceCompat"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/nixuniversalsdk\/devicestatus\/equatable-implementations"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A framework to allow integration of Nix devices into third party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/ERROR_UNSUPPORTED_DEVICE":{"role":"symbol","title":"DeviceStatus.ERROR_UNSUPPORTED_DEVICE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_UNSUPPORTED_DEVICE"}],"abstract":[{"type":"text","text":"The device connection attempt was cancelled because the specified device type was not supported."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_UNSUPPORTED_DEVICE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceStatusERROR_UNSUPPORTED_DEVICE"}],"url":"\/documentation\/nixuniversalsdk\/devicestatus\/error_unsupported_device"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/ERROR_MAX_ATTEMPTS":{"role":"symbol","title":"DeviceStatus.ERROR_MAX_ATTEMPTS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_MAX_ATTEMPTS"}],"abstract":[{"type":"text","text":"The device connection attempt was cancelled because the maximum number of attempts was reached."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_MAX_ATTEMPTS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceStatusERROR_MAX_ATTEMPTS"}],"url":"\/documentation\/nixuniversalsdk\/devicestatus\/error_max_attempts"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/SUCCESS":{"role":"symbol","title":"DeviceStatus.SUCCESS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SUCCESS"}],"abstract":[{"type":"text","text":"The device has disconnected normally (e.g. - via calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/disconnect()"},{"type":"text","text":")."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/SUCCESS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceStatusSUCCESS"}],"url":"\/documentation\/nixuniversalsdk\/devicestatus\/success"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk\/devicestatus\/init(rawvalue:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate":{"role":"symbol","title":"DeviceStateDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceStateDelegate"}],"abstract":[{"type":"text","text":"Definition for a callback from an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" instance on a connection state change, battery state change, or external power state change."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceStateDelegate"}],"url":"\/documentation\/nixuniversalsdk\/devicestatedelegate"},"doc://com.nixsensor.universalsdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ"},"doc://com.nixsensor.universalsdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SH"},"doc://com.nixsensor.universalsdk/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DeviceStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DeviceStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DeviceStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_DROPPED_CONNECTION","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_INTERNAL","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_MAX_ATTEMPTS","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_TIMEOUT","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_UNAUTHORIZED","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_UNSUPPORTED_DEVICE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/SUCCESS"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/title","value":"DeviceStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/fragments","value":[{"kind":"identifier","text":"DeviceStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_TIMEOUT\/title","value":"DeviceStatusERROR_TIMEOUT"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_TIMEOUT\/fragments","value":[{"kind":"identifier","text":"DeviceStatusERROR_TIMEOUT"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1disconnect()\/title","value":"disconnect"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1disconnect()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disconnect"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_DROPPED_CONNECTION\/title","value":"DeviceStatusERROR_DROPPED_CONNECTION"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_DROPPED_CONNECTION\/fragments","value":[{"kind":"identifier","text":"DeviceStatusERROR_DROPPED_CONNECTION"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_UNAUTHORIZED\/title","value":"DeviceStatusERROR_UNAUTHORIZED"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_UNAUTHORIZED\/fragments","value":[{"kind":"identifier","text":"DeviceStatusERROR_UNAUTHORIZED"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_INTERNAL\/title","value":"DeviceStatusERROR_INTERNAL"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_INTERNAL\/fragments","value":[{"kind":"identifier","text":"DeviceStatusERROR_INTERNAL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","value":"IDeviceCompat"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","value":[{"kind":"identifier","text":"IDeviceCompat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_UNSUPPORTED_DEVICE\/title","value":"DeviceStatusERROR_UNSUPPORTED_DEVICE"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_UNSUPPORTED_DEVICE\/fragments","value":[{"kind":"identifier","text":"DeviceStatusERROR_UNSUPPORTED_DEVICE"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_MAX_ATTEMPTS\/title","value":"DeviceStatusERROR_MAX_ATTEMPTS"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_MAX_ATTEMPTS\/fragments","value":[{"kind":"identifier","text":"DeviceStatusERROR_MAX_ATTEMPTS"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1SUCCESS\/title","value":"DeviceStatusSUCCESS"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1SUCCESS\/fragments","value":[{"kind":"identifier","text":"DeviceStatusSUCCESS"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/title","value":"DeviceStateDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/fragments","value":[{"kind":"identifier","text":"DeviceStateDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}