{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/batteryLevel","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/extPowerState","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationDue","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationEnabled","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationMaxDelta","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/firmwareVersion","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hapticFeedbackEnabled","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hardwareVersion","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hasOptions","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/id","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/interfaceType","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/name","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/note","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/powerState","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesDensity","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesSpectral","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/referenceDate","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/referenceTemperature","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rgbFeedbackEnabled","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rssi","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/scanCount","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/scanTemperature","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/sdkId","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/serialNumber","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/softwareVersion","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/state","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportedModes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportedReferences","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsFieldCalibration","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsHapticFeedback","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsRgbFeedback","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsTemperatureCompensation","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/temperatureCompensationEnabled","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/connect(delegate:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/disconnect()","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/invalidateFieldCalibration(completion:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/isModeSupported(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/isTileStringValid(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/ledTest(completion:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(completion:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(modes:completion:)-18cni","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesColor(illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesColor(reference:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/runFieldCalibration(tileString:completion:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setFieldCalibrationEnabled(_:completion:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setHapticFeedbackEnabled(_:completion:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setRgbFeedbackEnabled(_:completion:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setTemperatureCompensationEnabled(_:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"metadata":{"role":"symbol","title":"IDeviceCompat","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"IDeviceCompat"}],"externalID":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","symbolKind":"protocol","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDeviceCompat"}]},"abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference"},{"type":"text","text":" objects are found nearby using the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","isActive":true,"type":"reference"},{"text":".","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IDeviceCompat"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/idevicecompat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/idevicecompat"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/interfaceType":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/interfacetype","type":"topic","title":"interfaceType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/interfaceType","required":true,"role":"symbol","navigatorTitle":[{"text":"interfaceType","kind":"identifier"}],"abstract":[{"text":"Interface \/ connection type for this device","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"interfaceType","kind":"identifier"},{"kind":"text","text":": "},{"text":"InterfaceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@InterfaceType","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/fieldCalibrationDue":{"abstract":[{"text":"Flag to indicate if in-field calibration is recommended for this device at this time (if supported). This value is only valid after opening a connection and is a function of both time and ambient temperature. This value also updates each time a measurement is completed.","type":"text"}],"role":"symbol","type":"topic","title":"fieldCalibrationDue","navigatorTitle":[{"text":"fieldCalibrationDue","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fieldCalibrationDue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/fieldcalibrationdue","required":true,"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationDue"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/MINI3":{"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype\/mini3","role":"symbol","abstract":[{"text":"Type for Nix Mini 3 colorimeter","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI3","title":"DeviceType.MINI3","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"MINI3","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceTypeMINI3"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/invalidateFieldCalibration(completion:)":{"abstract":[{"text":"Invalidates current field calibration date, so that ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationDue","isActive":true},{"text":" is reported as ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", if supported by the device.","type":"text"}],"role":"symbol","title":"invalidateFieldCalibration(completion:)","type":"topic","navigatorTitle":[{"text":"invalidateFieldCalibrationWithCompletion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidateFieldCalibration","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","kind":"typeIdentifier","text":"DeviceResultCallback"},{"kind":"text","text":")"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/invalidatefieldcalibration(completion:)","required":true,"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/invalidateFieldCalibration(completion:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"abstract":[{"text":"Class used to discover nearby Nix devices","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceScanner","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","title":"DeviceScanner","url":"\/documentation\/nixuniversalsdk\/devicescanner","role":"symbol","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/supportsTemperatureCompensation":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportsTemperatureCompensation"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"supportsTemperatureCompensation","kind":"symbol","navigatorTitle":[{"text":"supportsTemperatureCompensation","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/supportstemperaturecompensation","abstract":[{"type":"text","text":"Flag to indicate if this device supports automatic temperature compensation to correct for small changes in ambient temperature."}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsTemperatureCompensation"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/setRgbFeedbackEnabled(_:completion:)":{"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/setrgbfeedbackenabled(_:completion:)","required":true,"navigatorTitle":[{"text":"setRgbFeedbackEnabled:completion:","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setRgbFeedbackEnabled(_:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRgbFeedbackEnabled"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeviceResultCallback","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"text":"Set the value for ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rgbFeedbackEnabled","isActive":true,"type":"reference"},{"type":"text","text":". This method is asynchronous and will return immediately."}],"role":"symbol","title":"setRgbFeedbackEnabled(_:completion:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/SPECTRO2":{"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype\/spectro2","role":"symbol","abstract":[{"type":"text","text":"Type for Nix Spectro 2 spectrophotometer"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/SPECTRO2","title":"DeviceType.SPECTRO2","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"SPECTRO2","kind":"identifier"}],"navigatorTitle":[{"text":"DeviceTypeSPECTRO2","kind":"identifier"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/referenceDate":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/referencedate","title":"referenceDate","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/referenceDate","required":true,"role":"symbol","navigatorTitle":[{"text":"referenceDate","kind":"identifier"}],"abstract":[{"text":"Date that the last in-field normalization was last performed, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if this device does not support this feature.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"referenceDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/rgbFeedbackEnabled":{"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/rgbfeedbackenabled","required":true,"navigatorTitle":[{"text":"rgbFeedbackEnabled","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rgbFeedbackEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rgbFeedbackEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"text":"Flag to indicate if device RGB feedback is enabled.","type":"text"}],"role":"symbol","title":"rgbFeedbackEnabled"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/disconnect()":{"navigatorTitle":[{"text":"disconnect","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/disconnect()","abstract":[{"type":"text","text":"Disconnect from this Nix device, or cancel a connection attempt currently in progress."}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/disconnect()","title":"disconnect()","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"disconnect","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/batteryLevel":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/batterylevel","type":"topic","title":"batteryLevel","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/batteryLevel","required":true,"role":"symbol","navigatorTitle":[{"text":"batteryLevel","kind":"identifier"}],"abstract":[{"text":"Current battery level for this device (0 - 100), or ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if not available. "},{"type":"codeVoice","code":"NSNumber"},{"type":"text","text":" contains an integer value. The value is valid only after a connection has successfully been opened."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"batteryLevel"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/supportsRgbFeedback":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportsRgbFeedback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","title":"supportsRgbFeedback","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"supportsRgbFeedback"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/supportsrgbfeedback","abstract":[{"type":"text","text":"Flag to indicate if the device supports built-in RGB feedback."}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsRgbFeedback"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/firmwareVersion":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/firmwareversion","title":"firmwareVersion","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/firmwareVersion","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"firmwareVersion"}],"abstract":[{"text":"Firmware version of this device. The value is valid only after a connection has successfully been opened.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"firmwareVersion"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(cs)DeviceVersion","text":"DeviceVersion","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/scanTemperature":{"required":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/scanTemperature","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/scantemperature","type":"topic","title":"scanTemperature","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"scanTemperature","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"text":"scanTemperature","kind":"identifier"}],"abstract":[{"text":"Last known temperature of the device, corresponding to the most recently completed scan since the device was connected. ","type":"text"},{"type":"codeVoice","code":"NSNumber"},{"type":"text","text":" contains a "},{"code":"Float","type":"codeVoice"},{"type":"text","text":" value. Value is "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the device does not support this feature. This value is only valid if the device is connected and a measurement has completed."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/ledTest(completion:)":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/ledtest(completion:)","type":"topic","title":"ledTest(completion:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/ledTest(completion:)","required":true,"role":"symbol","navigatorTitle":[{"text":"ledTest:","kind":"identifier"}],"abstract":[{"type":"text","text":"Manually run a LED test routine. On devices featuring RGB feedback, this will use the RGB LEDs. On other devices, this will flash the white LEDs. This method is asynchronous and will return immediately."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"ledTest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DeviceResultCallback","kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka"},{"text":")","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/providesDensity":{"required":true,"title":"providesDensity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"providesDensity","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/providesdensity","navigatorTitle":[{"text":"providesDensity","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Flag to indicate if this device type provides density information in its supplied "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"},{"type":"text","text":" results."}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesDensity","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/connect(delegate:)":{"kind":"symbol","navigatorTitle":[{"text":"connect:","kind":"identifier"}],"type":"topic","title":"connect(delegate:)","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/connect(delegate:)","required":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/connect(delegate:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)DeviceStateDelegate","text":"DeviceStateDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Open a connection to this Nix device. This operation is asynchronous and this method returns immediately. Status of this operation is updated via the provided "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","isActive":true,"type":"reference"},{"text":" callback.","type":"text"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/hapticFeedbackEnabled":{"kind":"symbol","required":true,"navigatorTitle":[{"text":"hapticFeedbackEnabled","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Flag to indicate if device haptic feedback is enabled."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hapticFeedbackEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hapticFeedbackEnabled","title":"hapticFeedbackEnabled","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/hapticfeedbackenabled","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate":{"navigatorTitle":[{"text":"DeviceStateDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","abstract":[{"type":"text","text":"Definition for a callback from an "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference"},{"text":" instance on a connection state change, battery state change, or external power state change.","type":"text"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicestatedelegate","title":"DeviceStateDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceStateDelegate","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/fieldCalibrationMaxDelta":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationMaxDelta","navigatorTitle":[{"text":"fieldCalibrationMaxDelta","kind":"identifier"}],"required":true,"title":"fieldCalibrationMaxDelta","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fieldCalibrationMaxDelta","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/fieldcalibrationmaxdelta","abstract":[{"text":"Maximum Delta E threshold used when performing in-field calibration (if supported), or NaN if the device does not support this operation. If a difference from the reference greater than this value is detected during ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/runFieldCalibration(tileString:completion:)"},{"type":"text","text":", the command will fail with status "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus\/ERROR_SCAN_DELTA","type":"reference"},{"text":".","type":"text"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/setTemperatureCompensationEnabled(_:completion:)":{"navigatorTitle":[{"text":"setTemperatureCompensationEnabled:completion:","kind":"identifier"}],"title":"setTemperatureCompensationEnabled(_:completion:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setTemperatureCompensationEnabled(_:completion:)","abstract":[{"type":"text","text":"Set the value for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/temperatureCompensationEnabled"},{"type":"text","text":". This method is asynchronous and will return immediately."}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/settemperaturecompensationenabled(_:completion:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setTemperatureCompensationEnabled","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"DeviceResultCallback","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"type":"text","text":"A framework to allow integration of Nix devices into third party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/note":{"required":true,"type":"topic","kind":"symbol","navigatorTitle":[{"text":"note","kind":"identifier"}],"title":"note","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/note","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"note"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/note","abstract":[{"type":"text","text":"Factory note for this device, containing allocation code. The value is valid only after a connection has successfully been opened."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","navigatorTitle":[{"text":"ScanMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/scanmode","title":"ScanMode","type":"topic","abstract":[{"text":"Enum to describe the measurement modes used by Nix devices","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ScanMode","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/name":{"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/name","title":"name","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/name","abstract":[{"text":"Name for this device","type":"text"}],"type":"topic","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"name"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/fieldCalibrationEnabled":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationEnabled","kind":"symbol","abstract":[{"type":"text","text":"Flag to indicate if in-field calibration results are applied ("},{"type":"codeVoice","code":"true"},{"text":") or bypassed (","type":"text"},{"type":"codeVoice","code":"false"},{"text":") when evaluating the final calibrated measurement result. Value is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" by default if supported by the device. It is recommended to leave this set to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" if supported.","type":"text"}],"required":true,"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/fieldcalibrationenabled","title":"fieldCalibrationEnabled","navigatorTitle":[{"text":"fieldCalibrationEnabled","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fieldCalibrationEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/scanCount":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/scancount","title":"scanCount","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/scanCount","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"scanCount"}],"abstract":[{"type":"text","text":"Lifetime scan count for this device, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if this device does not support this feature. "},{"code":"NSNumber","type":"codeVoice"},{"text":" contains an ","type":"text"},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/CommandStatus/ERROR_NOT_SUPPORTED":{"url":"\/documentation\/nixuniversalsdk\/commandstatus\/error_not_supported","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus\/ERROR_NOT_SUPPORTED","navigatorTitle":[{"text":"CommandStatusERROR_NOT_SUPPORTED","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ERROR_NOT_SUPPORTED","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Status code indicating that the command was aborted because the it was not supported by the Nix device instance.","type":"text"}],"title":"CommandStatus.ERROR_NOT_SUPPORTED"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/CommandStatus/ERROR_SCAN_DELTA":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus\/ERROR_SCAN_DELTA","navigatorTitle":[{"text":"CommandStatusERROR_SCAN_DELTA","kind":"identifier"}],"title":"CommandStatus.ERROR_SCAN_DELTA","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ERROR_SCAN_DELTA","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/commandstatus\/error_scan_delta","abstract":[{"text":"Status code indicating that the in-field calibration operation failed due to high delta E (i.e. - the calibration reference tile could not be verified by its color value). This status is only possible after a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/runFieldCalibration(tileString:completion:)"},{"type":"text","text":" command."}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/isModeSupported(_:)":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/ismodesupported(_:)","navigatorTitle":[{"text":"isModeSupported:","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isModeSupported","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ScanMode","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isModeSupported(_:)","required":true,"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/isModeSupported(_:)","abstract":[{"text":"Helper to check if a particular scan mode is supported by this device (i.e. - checks if the mode is present in the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportedModes"},{"type":"text","text":" list). This value is valid only after a connection has successfully been opened."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/temperatureCompensationEnabled":{"abstract":[{"text":"Flag to indicate if ambient temperature compensation \/ correction is applied (","type":"text"},{"type":"codeVoice","code":"true"},{"text":") or bypassed (","type":"text"},{"code":"false","type":"codeVoice"},{"text":") when evaluating the final calibrated measurement. Value is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" by default if supported by the device. It is recommended to leave this set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if supported.","type":"text"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"temperatureCompensationEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"temperatureCompensationEnabled"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/temperatureCompensationEnabled","title":"temperatureCompensationEnabled","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/temperaturecompensationenabled","role":"symbol","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/setFieldCalibrationEnabled(_:completion:)":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/setfieldcalibrationenabled(_:completion:)","type":"topic","title":"setFieldCalibrationEnabled(_:completion:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setFieldCalibrationEnabled(_:completion:)","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setFieldCalibrationEnabled:completion:"}],"abstract":[{"text":"Set the value for ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationEnabled","type":"reference","isActive":true},{"text":". This method is asynchronous and will return immediately.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFieldCalibrationEnabled","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DeviceResultCallback","kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka"},{"text":")","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/extPowerState":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/extpowerstate","title":"extPowerState","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/extPowerState","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"extPowerState"}],"abstract":[{"type":"text","text":"External power connection state for this device. The value is valid only after a connection has successfully been opened."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"extPowerState","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/rssi":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"rssi","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"rssi"}],"abstract":[{"type":"text","text":"Signal strength for this device"}],"kind":"symbol","type":"topic","title":"rssi","role":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/rssi","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rssi","required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/hardwareVersion":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/hardwareversion","type":"topic","title":"hardwareVersion","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hardwareVersion","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hardwareVersion"}],"abstract":[{"text":"Hardware version of this device. The value is valid only after a connection has successfully been opened.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hardwareVersion"},{"text":": ","kind":"text"},{"text":"DeviceVersion","preciseIdentifier":"c:@M@NixUniversalSDK@objc(cs)DeviceVersion","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData":{"abstract":[{"text":"Protocol defining the properties and methods provided by Nix device measurements. These objects are provided in the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","isActive":true},{"text":" callback after a measurement is taken using an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"text":" instance, or can be reconstructed from raw string data using ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"IMeasurementData","kind":"identifier"}],"title":"IMeasurementData","url":"\/documentation\/nixuniversalsdk\/imeasurementdata","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IMeasurementData","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/isTileStringValid(_:)":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/istilestringvalid(_:)","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isTileStringValid:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isTileStringValid"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isTileStringValid(_:)","abstract":[{"type":"text","text":"Check if the formatting of the reference tile string data matches the expected format for this device, or "},{"type":"codeVoice","code":"false"},{"type":"text","text":" if the device does not support this feature."}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/isTileStringValid(_:)","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/providesSpectral":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/providesspectral","title":"providesSpectral","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesSpectral","required":true,"role":"symbol","navigatorTitle":[{"text":"providesSpectral","kind":"identifier"}],"abstract":[{"type":"text","text":"Flag to indicate if this device type provides spectral information in its supplied "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","type":"reference","isActive":true},{"type":"text","text":" results."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"providesSpectral","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/measure(completion:)":{"required":true,"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/measure(completion:)","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(completion:)","navigatorTitle":[{"kind":"identifier","text":"measure:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"measure"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","text":"DeviceResultCallback","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","abstract":[{"text":"Run a measurement for all supported scan modes. This method is asynchronous and will return immediately.","type":"text"}],"title":"measure(completion:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/sdkId":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/sdkid","type":"topic","title":"sdkId","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/sdkId","required":true,"role":"symbol","navigatorTitle":[{"text":"sdkId","kind":"identifier"}],"abstract":[{"text":"Build ID for this ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"reference","isActive":true},{"text":" binary","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/runFieldCalibration(tileString:completion:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/runFieldCalibration(tileString:completion:)","navigatorTitle":[{"text":"runFieldCalibration:completion:","kind":"identifier"}],"required":true,"title":"runFieldCalibration(tileString:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"runFieldCalibration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tileString","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DeviceResultCallback","kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Start field calibration using provided reference tile, if supported. Upon executing this command, the scan of the reference tile will begin immediately. The user MUST be prompted to place the device onto the reference tile BEFORE this method is executed. This method is asynchronous and will return immediately."},{"type":"text","text":" "},{"text":"This command requires data from the reference tile QR code. As the format varies between different device types, the string data should be provided exactly as decoded from the QR code.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/runfieldcalibration(tilestring:completion:)","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/state":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/state","title":"state","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/state","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"state"}],"abstract":[{"type":"text","text":"Current state of this device"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DeviceState","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceState","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/referenceTemperature":{"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/referencetemperature","role":"symbol","abstract":[{"type":"text","text":"Baseline temperature for this device. Corresponds to in-field normalization temperature for "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/SPECTRO2","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI3"},{"text":", or factory temperature for others. ","type":"text"},{"code":"NSNumber","type":"codeVoice"},{"text":" contains a ","type":"text"},{"code":"Float","type":"codeVoice"},{"text":" value. Value is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the device does not support this feature. The value is valid only after a connection has successfully been opened.","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/referenceTemperature","title":"referenceTemperature","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"referenceTemperature"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"referenceTemperature","kind":"identifier"}],"type":"topic","required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/hasOptions":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hasOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","title":"hasOptions","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"hasOptions"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/hasoptions","abstract":[{"type":"text","text":"Helper function to describe if any on-device options are available. Value is "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if any one of "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsFieldCalibration","type":"reference","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsTemperatureCompensation","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsHapticFeedback","isActive":true,"type":"reference"},{"type":"text","text":", or "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsRgbFeedback","isActive":true,"type":"reference"},{"type":"text","text":" is "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hasOptions"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/supportsFieldCalibration":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportsFieldCalibration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","title":"supportsFieldCalibration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"supportsFieldCalibration"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/supportsfieldcalibration","abstract":[{"type":"text","text":"Flag to indicate if this device supports in-field calibration using the provided reference tile."}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsFieldCalibration"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/softwareVersion":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/softwareversion","type":"topic","title":"softwareVersion","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/softwareVersion","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"softwareVersion"}],"abstract":[{"text":"Software version of this device. The value is valid only after a connection has successfully been opened.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"softwareVersion"},{"text":": ","kind":"text"},{"text":"DeviceVersion","preciseIdentifier":"c:@M@NixUniversalSDK@objc(cs)DeviceVersion","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/providesColor(illuminant:observer:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"providesColor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"illuminant"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant"},{"text":", ","kind":"text"},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/providescolor(illuminant:observer:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesColor(illuminant:observer:)","navigatorTitle":[{"kind":"identifier","text":"providesColorForIlluminant:andObserver:"}],"type":"topic","role":"symbol","title":"providesColor(illuminant:observer:)","abstract":[{"type":"text","text":"Helper to check if a particular reference white point is supported by the colorimetry data from this device (i.e - checks if the reference is present in the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportedReferences"},{"text":" list`).","type":"text"}],"required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/supportedReferences":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedReferences","kind":"identifier"},{"kind":"text","text":": "},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":">"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/supportedreferences","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportedReferences","navigatorTitle":[{"text":"supportedReferences","kind":"identifier"}],"type":"topic","role":"symbol","title":"supportedReferences","abstract":[{"text":"List of supported reference white points for the colorimetry data available from the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"},{"type":"text","text":" results provided by this device (set of "},{"type":"codeVoice","code":"NSNumber"},{"type":"text","text":" containing "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","isActive":true,"type":"reference"},{"type":"text","text":" values)"}],"required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/serialNumber":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/serialnumber","title":"serialNumber","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/serialNumber","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"serialNumber"}],"abstract":[{"type":"text","text":"Serial number for this device. The value is valid only after a connection has successfully been opened."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"serialNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/type":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/type","type":"topic","title":"type","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/type","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"type"}],"abstract":[{"text":"Type for this device","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"text":"DeviceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/measure(modes:completion:)-18cni":{"required":true,"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/measure(modes:completion:)-18cni","role":"symbol","defaultImplementations":1,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(modes:completion:)-18cni","navigatorTitle":[{"text":"measureWithModes:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"measure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modes"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","text":"DeviceResultCallback"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","abstract":[{"text":"Run a measurement in the specified scan modes. If any unsupported modes are selected, the measurement will fail with status code ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus\/ERROR_NOT_SUPPORTED"},{"text":". This method is asynchronous and will return immediately.","type":"text"}],"title":"measure(modes:completion:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/setHapticFeedbackEnabled(_:completion:)":{"kind":"symbol","required":true,"navigatorTitle":[{"text":"setHapticFeedbackEnabled:completion:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Set the value for ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hapticFeedbackEnabled","isActive":true,"type":"reference"},{"type":"text","text":". This method is asynchronous and will return immediately."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setHapticFeedbackEnabled","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DeviceResultCallback","preciseIdentifier":"s:15NixUniversalSDK20DeviceResultCallbacka","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setHapticFeedbackEnabled(_:completion:)","title":"setHapticFeedbackEnabled(_:completion:)","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/sethapticfeedbackenabled(_:completion:)","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/powerState":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/powerState","navigatorTitle":[{"kind":"identifier","text":"powerState"}],"required":true,"title":"powerState","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"powerState"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/powerstate","abstract":[{"type":"text","text":"Flag: "},{"code":"true","type":"codeVoice"},{"type":"text","text":" if sufficient power is available to complete a measurement, "},{"code":"false","type":"codeVoice"},{"text":" if a measurement will be aborted (function of external power connection and battery level)","type":"text"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/supportedModes":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedModes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":">"}],"title":"supportedModes","abstract":[{"text":"List of scan modes that are supported by this device (set of ","type":"text"},{"code":"NSNumber","type":"codeVoice"},{"type":"text","text":" containing "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","isActive":true},{"text":" values). The list is valid only after a connection has successfully been opened.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/supportedmodes","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportedModes","type":"topic","role":"symbol","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"supportedModes"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/providesColor(reference:)":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/providescolor(reference:)","title":"providesColor(reference:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesColor(reference:)","required":true,"role":"symbol","navigatorTitle":[{"text":"providesColorWithReference:","kind":"identifier"}],"abstract":[{"type":"text","text":"Helper to check if a particular reference white point is supported by the colorimetry data from this device (i.e - checks if the reference is present in the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportedReferences","type":"reference","isActive":true},{"type":"text","text":" list`)."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"providesColor","kind":"identifier"},{"kind":"text","text":"("},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ReferenceWhite","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/supportsHapticFeedback":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsHapticFeedback","navigatorTitle":[{"kind":"identifier","text":"supportsHapticFeedback"}],"required":true,"title":"supportsHapticFeedback","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportsHapticFeedback","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/supportshapticfeedback","abstract":[{"text":"Flag to indicate if the device supports built-in haptic feedback.","type":"text"}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"abstract":[{"text":"Protocol describing the supported properties and methods for a Nix device. ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference","isActive":true},{"type":"text","text":" objects are found nearby using the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IDeviceCompat","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IDeviceCompat"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","title":"IDeviceCompat","url":"\/documentation\/nixuniversalsdk\/idevicecompat","role":"symbol","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"kind":"symbol","abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","title":"ReferenceWhite","role":"symbol","url":"\/documentation\/nixuniversalsdk\/referencewhite","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReferenceWhite","kind":"identifier"}],"navigatorTitle":[{"text":"ReferenceWhite","kind":"identifier"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/id":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/id","type":"topic","title":"id","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/id","required":true,"role":"symbol","navigatorTitle":[{"text":"id","kind":"identifier"}],"abstract":[{"type":"text","text":"Unique identifier for this device"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"IDeviceCompat","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"value":[{"text":"IDeviceCompat","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"IDeviceCompat","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/batteryLevel","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/extPowerState","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationDue","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationEnabled","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/fieldCalibrationMaxDelta","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/firmwareVersion","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hapticFeedbackEnabled","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hardwareVersion","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/hasOptions","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/id","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/interfaceType","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/name","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/note","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/powerState","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesDensity","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesSpectral","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/referenceDate","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/referenceTemperature","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rgbFeedbackEnabled","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rssi","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/scanCount","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/scanTemperature","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/sdkId","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/serialNumber","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/softwareVersion","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/state","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportedModes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportedReferences","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsFieldCalibration","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsHapticFeedback","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsRgbFeedback","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/supportsTemperatureCompensation","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/temperatureCompensationEnabled","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/type"]},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/connect(delegate:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/disconnect()","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/invalidateFieldCalibration(completion:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/isModeSupported(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/isTileStringValid(_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/ledTest(completion:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(completion:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/measure(modes:completion:)-18cni","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesColor(illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/providesColor(reference:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/runFieldCalibration(tileString:completion:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setFieldCalibrationEnabled(_:completion:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setHapticFeedbackEnabled(_:completion:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setRgbFeedbackEnabled(_:completion:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/setTemperatureCompensationEnabled(_:completion:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"IDeviceCompat","kind":"identifier"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1interfaceType\/title","value":"interfaceType"},{"value":[{"kind":"identifier","text":"interfaceType"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1interfaceType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1fieldCalibrationDue\/title","value":"fieldCalibrationDue"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1fieldCalibrationDue\/fragments","value":[{"text":"fieldCalibrationDue","kind":"identifier"}]},{"value":"DeviceTypeMINI3","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1MINI3\/title"},{"value":[{"text":"DeviceTypeMINI3","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1MINI3\/fragments"},{"value":"invalidateFieldCalibrationWithCompletion:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1invalidateFieldCalibration(completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1invalidateFieldCalibration(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"invalidateFieldCalibrationWithCompletion:","kind":"identifier"}]},{"value":"DeviceScanner","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","value":[{"kind":"identifier","text":"DeviceScanner"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsTemperatureCompensation\/title","value":"supportsTemperatureCompensation"},{"value":[{"kind":"identifier","text":"supportsTemperatureCompensation"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsTemperatureCompensation\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setRgbFeedbackEnabled(_:completion:)\/title","value":"setRgbFeedbackEnabled:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"setRgbFeedbackEnabled:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setRgbFeedbackEnabled(_:completion:)\/fragments"},{"value":"DeviceTypeSPECTRO2","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1SPECTRO2\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1SPECTRO2\/fragments","value":[{"kind":"identifier","text":"DeviceTypeSPECTRO2"}],"op":"replace"},{"value":"referenceDate","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1referenceDate\/title"},{"value":[{"kind":"identifier","text":"referenceDate"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1referenceDate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1rgbFeedbackEnabled\/title","value":"rgbFeedbackEnabled"},{"op":"replace","value":[{"kind":"identifier","text":"rgbFeedbackEnabled"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1rgbFeedbackEnabled\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1disconnect()\/title","value":"disconnect","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disconnect"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1disconnect()\/fragments"},{"op":"replace","value":"batteryLevel","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1batteryLevel\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1batteryLevel\/fragments","value":[{"kind":"identifier","text":"batteryLevel"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsRgbFeedback\/title","op":"replace","value":"supportsRgbFeedback"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsRgbFeedback\/fragments","value":[{"kind":"identifier","text":"supportsRgbFeedback"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1firmwareVersion\/title","value":"firmwareVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1firmwareVersion\/fragments","value":[{"text":"firmwareVersion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1scanTemperature\/title","value":"scanTemperature"},{"value":[{"text":"scanTemperature","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1scanTemperature\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1ledTest(completion:)\/title","value":"ledTest:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"ledTest:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1ledTest(completion:)\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1providesDensity\/title","value":"providesDensity","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1providesDensity\/fragments","value":[{"text":"providesDensity","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1connect(delegate:)\/title","value":"connect:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1connect(delegate:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"connect:"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1hapticFeedbackEnabled\/title","value":"hapticFeedbackEnabled","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"hapticFeedbackEnabled"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1hapticFeedbackEnabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/title","value":"DeviceStateDelegate"},{"value":[{"kind":"identifier","text":"DeviceStateDelegate"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1fieldCalibrationMaxDelta\/title","value":"fieldCalibrationMaxDelta"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1fieldCalibrationMaxDelta\/fragments","op":"replace","value":[{"text":"fieldCalibrationMaxDelta","kind":"identifier"}]},{"op":"replace","value":"setTemperatureCompensationEnabled:completion:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setTemperatureCompensationEnabled(_:completion:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setTemperatureCompensationEnabled(_:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setTemperatureCompensationEnabled:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1note\/title","value":"note","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1note\/fragments","value":[{"text":"note","kind":"identifier"}],"op":"replace"},{"value":"ScanMode","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments","value":[{"text":"ScanMode","kind":"identifier"}]},{"value":"name","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1name\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"name"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1name\/fragments"},{"op":"replace","value":"fieldCalibrationEnabled","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1fieldCalibrationEnabled\/title"},{"value":[{"text":"fieldCalibrationEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1fieldCalibrationEnabled\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1scanCount\/title","value":"scanCount"},{"value":[{"text":"scanCount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1scanCount\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus~1ERROR_NOT_SUPPORTED\/title","op":"replace","value":"CommandStatusERROR_NOT_SUPPORTED"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus~1ERROR_NOT_SUPPORTED\/fragments","op":"replace","value":[{"text":"CommandStatusERROR_NOT_SUPPORTED","kind":"identifier"}]},{"value":"CommandStatusERROR_SCAN_DELTA","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus~1ERROR_SCAN_DELTA\/title","op":"replace"},{"value":[{"text":"CommandStatusERROR_SCAN_DELTA","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus~1ERROR_SCAN_DELTA\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1isModeSupported(_:)\/title","value":"isModeSupported:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1isModeSupported(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isModeSupported:"}]},{"op":"replace","value":"temperatureCompensationEnabled","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1temperatureCompensationEnabled\/title"},{"value":[{"text":"temperatureCompensationEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1temperatureCompensationEnabled\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setFieldCalibrationEnabled(_:completion:)\/title","value":"setFieldCalibrationEnabled:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setFieldCalibrationEnabled(_:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setFieldCalibrationEnabled:completion:","kind":"identifier"}],"op":"replace"},{"value":"extPowerState","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1extPowerState\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1extPowerState\/fragments","value":[{"kind":"identifier","text":"extPowerState"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1rssi\/title","value":"rssi","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"rssi"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1rssi\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1hardwareVersion\/title","value":"hardwareVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1hardwareVersion\/fragments","value":[{"text":"hardwareVersion","kind":"identifier"}]},{"value":"IMeasurementData","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/fragments","value":[{"kind":"identifier","text":"IMeasurementData"}]},{"op":"replace","value":"isTileStringValid:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1isTileStringValid(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isTileStringValid:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1isTileStringValid(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1providesSpectral\/title","value":"providesSpectral","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1providesSpectral\/fragments","value":[{"kind":"identifier","text":"providesSpectral"}],"op":"replace"},{"value":"measure:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1measure(completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"measure:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1measure(completion:)\/fragments"},{"value":"sdkId","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1sdkId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"sdkId"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1sdkId\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1runFieldCalibration(tileString:completion:)\/title","op":"replace","value":"runFieldCalibration:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1runFieldCalibration(tileString:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"runFieldCalibration:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1state\/title","value":"state"},{"value":[{"text":"state","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1state\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1referenceTemperature\/title","value":"referenceTemperature","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1referenceTemperature\/fragments","op":"replace","value":[{"kind":"identifier","text":"referenceTemperature"}]},{"op":"replace","value":"hasOptions","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1hasOptions\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1hasOptions\/fragments","op":"replace","value":[{"text":"hasOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsFieldCalibration\/title","value":"supportsFieldCalibration"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsFieldCalibration\/fragments","value":[{"text":"supportsFieldCalibration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1softwareVersion\/title","op":"replace","value":"softwareVersion"},{"value":[{"text":"softwareVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1softwareVersion\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1providesColor(illuminant:observer:)\/title","value":"providesColorForIlluminant:andObserver:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1providesColor(illuminant:observer:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"providesColorForIlluminant:andObserver:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportedReferences\/title","value":"supportedReferences","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportedReferences\/fragments","value":[{"text":"supportedReferences","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1serialNumber\/title","op":"replace","value":"serialNumber"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1serialNumber\/fragments","op":"replace","value":[{"kind":"identifier","text":"serialNumber"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1type\/title","op":"replace","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"value":"measureWithModes:completion:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1measure(modes:completion:)-18cni\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1measure(modes:completion:)-18cni\/fragments","value":[{"kind":"text","text":"- "},{"text":"measureWithModes:completion:","kind":"identifier"}]},{"op":"replace","value":"setHapticFeedbackEnabled:completion:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setHapticFeedbackEnabled(_:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"setHapticFeedbackEnabled:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1setHapticFeedbackEnabled(_:completion:)\/fragments"},{"value":"powerState","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1powerState\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1powerState\/fragments","value":[{"text":"powerState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportedModes\/title","value":"supportedModes","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportedModes\/fragments","value":[{"text":"supportedModes","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"providesColorWithReference:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1providesColor(reference:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1providesColor(reference:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"providesColorWithReference:"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsHapticFeedback\/title","value":"supportsHapticFeedback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1supportsHapticFeedback\/fragments","value":[{"kind":"identifier","text":"supportsHapticFeedback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","value":"IDeviceCompat"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","op":"replace","value":[{"text":"IDeviceCompat","kind":"identifier"}]},{"value":"ReferenceWhite","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"kind":"identifier","text":"ReferenceWhite"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1id\/title","value":"id","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1id\/fragments","value":[{"text":"id","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}