{"abstract":[{"type":"text","text":"Flag indicating if this measurement provides density values. "},{"code":"Bool","type":"codeVoice"},{"type":"text","text":" value wrapped in a "},{"code":"NSNumber","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"providesDensity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Since 4.0.2"}],"type":"paragraph"}]}]}]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesDensity","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"]]},"metadata":{"navigatorTitle":[{"text":"providesDensity","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData(py)providesDensity","modules":[{"name":"NixUniversalSDK"}],"symbolKind":"property","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"providesDensity"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"}],"roleHeading":"Instance Property","role":"symbol","title":"providesDensity"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/imeasurementdata\/providesdensity"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/imeasurementdata\/providesdensity"]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceResultCallback":{"abstract":[{"type":"text","text":"Definition for a closure providing a command result, invoked after executing an asynchronous command on an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" instance."}],"type":"topic","navigatorTitle":[{"text":"DeviceResultCallback","kind":"identifier"}],"title":"DeviceResultCallback","url":"\/documentation\/nixuniversalsdk\/deviceresultcallback","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"DeviceResultCallback","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"type":"text","text":"A framework to allow integration of Nix devices into third party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/providesDensity":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"providesDensity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesDensity","abstract":[{"type":"text","text":"Flag indicating if this measurement provides density values. "},{"code":"Bool","type":"codeVoice"},{"text":" value wrapped in a ","type":"text"},{"code":"NSNumber","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/providesdensity","title":"providesDensity","type":"topic","navigatorTitle":[{"kind":"identifier","text":"providesDensity"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData/fromRaw(_:)":{"abstract":[{"text":"Reconstructs a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"},{"text":" instance from its raw string value, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the data is invalid."}],"type":"topic","title":"fromRaw(_:)","url":"\/documentation\/nixuniversalsdk\/measurementdata\/fromraw(_:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fromRaw","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"IMeasurementData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData"},{"kind":"text","text":"?"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"abstract":[{"text":"Protocol describing the supported properties and methods for a Nix device. ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference","isActive":true},{"type":"text","text":" objects are found nearby using the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IDeviceCompat","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IDeviceCompat"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","title":"IDeviceCompat","url":"\/documentation\/nixuniversalsdk\/idevicecompat","role":"symbol","type":"topic","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData":{"abstract":[{"text":"Protocol defining the properties and methods provided by Nix device measurements. These objects are provided in the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","isActive":true},{"text":" callback after a measurement is taken using an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"text":" instance, or can be reconstructed from raw string data using ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"IMeasurementData","kind":"identifier"}],"title":"IMeasurementData","url":"\/documentation\/nixuniversalsdk\/imeasurementdata","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IMeasurementData","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"providesDensity","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"providesDensity","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"text":"providesDensity","kind":"identifier"}],"platforms":["macOS"]}]},"op":"replace"},{"op":"replace","value":"providesDensity","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providesDensity\/title"},{"value":[{"text":"providesDensity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providesDensity\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","op":"replace","value":"IDeviceCompat"},{"value":[{"kind":"identifier","text":"IDeviceCompat"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/title","value":"IMeasurementData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/fragments","value":[{"kind":"identifier","text":"IMeasurementData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}