{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI3","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"text":"DeviceTypeMINI3","kind":"identifier"}],"title":"DeviceType.MINI3","roleHeading":"Case","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"MINI3","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@E@DeviceType@DeviceTypeMINI3","symbolKind":"case"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicetype\/mini3"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/devicetype\/mini3"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType"]]},"abstract":[{"text":"Type for Nix Mini 3 colorimeter","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"MINI3","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType":{"title":"DeviceType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","url":"\/documentation\/nixuniversalsdk\/devicetype","abstract":[{"text":"Enum to describe the supported Nix device types","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceType"}],"navigatorTitle":[{"text":"DeviceType","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"abstract":[{"type":"text","text":"A framework to allow integration of Nix devices into third party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/MINI3":{"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype\/mini3","role":"symbol","abstract":[{"text":"Type for Nix Mini 3 colorimeter","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/MINI3","title":"DeviceType.MINI3","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"MINI3","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceTypeMINI3"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DeviceTypeMINI3","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DeviceTypeMINI3","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DeviceTypeMINI3"}],"platforms":["macOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/title","value":"DeviceType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/fragments","value":[{"kind":"identifier","text":"DeviceType"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1MINI3\/title","value":"DeviceTypeMINI3","op":"replace"},{"op":"replace","value":[{"text":"DeviceTypeMINI3","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1MINI3\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}