{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/icolordata\/reference"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/icolordata\/reference"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/reference","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Reference white point for this color value."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"reference"}],"role":"symbol","title":"reference","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"}],"symbolKind":"property","externalID":"c:@M@NixUniversalSDK@objc(pl)IColorData(py)reference","required":true,"modules":[{"name":"NixUniversalSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A framework to allow integration of Nix devices into third party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData/reference":{"navigatorTitle":[{"kind":"identifier","text":"reference"}],"role":"symbol","title":"reference","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"}],"abstract":[{"type":"text","text":"Reference white point for this color value."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/reference","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nixuniversalsdk\/icolordata\/reference"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"role":"symbol","title":"IColorData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IColorData"}],"abstract":[{"type":"text","text":"Protocol describing colorimetry data"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IColorData"}],"url":"\/documentation\/nixuniversalsdk\/icolordata"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"role":"symbol","title":"ReferenceWhite","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReferenceWhite"}],"abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhite"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"reference"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"reference"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite"},{"kind":"text","text":" "},{"kind":"identifier","text":"reference"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1reference\/title","value":"reference"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1reference\/fragments","value":[{"kind":"identifier","text":"reference"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title","value":"IColorData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments","value":[{"kind":"identifier","text":"IColorData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","value":"ReferenceWhite"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"kind":"identifier","text":"ReferenceWhite"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}