{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIE94T"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/colordifferencetype\/cie94t"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/colordifferencetype\/cie94t"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE94T","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Color difference using CIE1994 equation using constants recommended for textiles."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIE94T"}],"title":"ColorDifferenceType.CIE94T","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@NixUniversalSDK@E@ColorDifferenceType@ColorDifferenceTypeCIE94T","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ColorDifferenceTypeCIE94T"}]},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType":{"role":"symbol","title":"ColorDifferenceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorDifferenceType"}],"abstract":[{"type":"text","text":"Enum describing the available color difference (delta E) equations."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ColorDifferenceType"}],"url":"\/documentation\/nixuniversalsdk\/colordifferencetype"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/CIE94T":{"role":"symbol","title":"ColorDifferenceType.CIE94T","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIE94T"}],"abstract":[{"type":"text","text":"Color difference using CIE1994 equation using constants recommended for textiles."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CIE94T","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ColorDifferenceTypeCIE94T"}],"url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/cie94t"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"role":"collection","title":"NixUniversalSDK","abstract":[{"type":"text","text":"A framework to allow integration of Nix devices into third party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ColorDifferenceTypeCIE94T"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ColorDifferenceTypeCIE94T"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ColorDifferenceTypeCIE94T"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/title","value":"ColorDifferenceType"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/fragments","value":[{"kind":"identifier","text":"ColorDifferenceType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CIE94T\/title","value":"ColorDifferenceTypeCIE94T"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CIE94T\/fragments","value":[{"kind":"identifier","text":"ColorDifferenceTypeCIE94T"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}